# Generated by Django 4.1.1 on 2022-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=25)),
                ('username', models.EmailField(default='null', max_length=40)),
                ('comment', models.TextField(max_length=1000)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
